{"NM":"fail 函数","CTS":[{"NT":"h","CT":"assert.fail 函数","CL":"#333"},{"NT":"p","CT":"assert.fail([message])","CL":"#333"},{"NT":"p","CT":"于 v0.1.21 版本被添加。","CL":"#333"},{"NT":"list","CTS":[{"NT":"li","CT":"``message``:string / Error | Default: ``'Failed'``","CL":"#333"}],"OL":false},{"NT":"p","CT":"抛出一个带有自定义错误信息或默认信息的``AssertionError``。如果输入的``message``参数是一个``Error``实例，则该实例会代替``AssertionError``被抛出。","CL":"#333"},{"NT":"code","LG":"javascript","CT":"import assert from 'node:assert/strict';\n\nassert.fail();\n// AssertionError [ERR_ASSERTION]: Failed\n\nassert.fail('boom');\n// AssertionError [ERR_ASSERTION]: boom\n\nassert.fail(new TypeError('need array'));\n// TypeError: need array"},{"NT":"p","CT":"在``assert.fail()``中传入两个或以上个数的参数是可能的，但这被废弃了。查看下篇文章获取详情。","CL":"#333"}]}